server:
  port: 8083
spring:
  application:
    name: authentication-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-support-agent
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: itsyou3004@gmail.com
    password: heop ykla iist rmbk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mongock:
  change-logs-scan-package: com.zapcom.configuration.DatabaseChangeLog
jwt:
  public:
    key:
    classpath: certs/public.pem
  private:
    key: classpath:certs/private.pem
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

