server:
  port: 8081
spring:
  application:
    name: authentication-service
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-support-agent
      auto-index-creation: true
    redis :
      host : localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: itsyou3004@gmail.com
    password: heop ykla iist rmbk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mongock:
  change-logs-scan-package: com.zapcom.configuration.DatabaseChangeLog
jwt:
  public:
    key:
    classpath: certs/public.pem
  private:
    key: classpath:certs/private.pem
  EXPIRATION_TIME: 86400000
  refreshTokenExpiration: 604800000
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.redis.core.RedisTemplate: DEBUG



